name: picads-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - pydantic
  - pydantic-settings
  - python-dotenv
  - pytest
  - httpx
  - pip
  - pip:
    - supabase
    - email-validator==2.1.0
    - stripe>=7.0.0 